# Generated by Django 5.2.9 on 2026-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Materiału')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='Kod SKU')),
                ('material_type', models.CharField(choices=[('RAW', 'Surowiec'), ('PACK', 'Opakowanie'), ('PRODUCT', 'Wyrób Gotowy')], max_length=20, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Materiał',
                'verbose_name_plural': 'Materiały',
            },
        ),
    ]
