# Generated by Django 5.2.9 on 2026-01-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='Numer Serii (LOT)')),
                ('manufacturing_date', models.DateField(verbose_name='Data Produkcji')),
                ('expiry_date', models.DateField(verbose_name='Data Ważności')),
                ('status', models.CharField(choices=[('QUARANTINE', 'Kwarantanna'), ('RELEASED', 'Zwolniony'), ('REJECTED', 'Odrzucony')], default='QUARANTINE', max_length=20, verbose_name='Status Jakościowy')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Materiał')),
            ],
            options={
                'verbose_name': 'Partia',
                'verbose_name_plural': 'Partie',
            },
        ),
    ]
