# Generated by Django 5.2.9 on 2026-01-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zużyta Ilość')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data Operacji')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='inventory.batch', verbose_name='Z Partii (Składnik)')),
                ('target_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consists_of', to='inventory.batch', verbose_name='Do Partii (Produkt)')),
            ],
            options={
                'verbose_name': 'Ruch / Zużycie',
                'verbose_name_plural': 'Traceability (Genealogia)',
            },
        ),
    ]
